WIP: Nipype update for BAW
Warnning: This could give an error with
Exception: Trait fixed_image_mask (Registration) (version 2.2.0 > required 2.1.0)
in BAW.